# Generated by Django 4.2.9 on 2026-01-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit_logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditentry",
            name="action",
            field=models.CharField(
                help_text="created, updated, deleted, synced", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="auditentry",
            name="channel",
            field=models.CharField(
                blank=True, help_text="Channel involved (if any)", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="auditentry",
            name="module",
            field=models.CharField(
                help_text="e.g., bookings, hotels, partners", max_length=100
            ),
        ),
    ]
